/**
 * Integration tests for the 5 ViSTR observation tools (vistr_video_tools.ts).
 *
 * Uses a REAL 2s/320x240/10fps H.264 test video generated by ffmpeg, and a
 * stubbed gateway + perception service. Exercises each tool's execute()
 * end-to-end: ffmpeg frame extraction, content blocks, details fields,
 * and error paths.
 */
import assert from "node:assert/strict";
import { test, loadExtension, createMockAPI, installFetch, testVideo, testImage, countImages, textBlocks } from "./harness.mjs";

async function makeTools(routes, observerBaseUrl = "http://observer.test") {
	process.env.VISTR_OBSERVER_BASE_URL = observerBaseUrl;
	process.env.VISTR_OBSERVER_API_KEY = "test-key";
	process.env.VISTR_OBSERVER_MODEL = "test-vlm";
	process.env.VISTR_OBSERVER_HEADERS_JSON = '{"x-observer-test":"configured"}';
	const mock = createMockAPI();
	const stub = installFetch(routes);
	(await loadExtension("/workspace/Spatial-Agent/4D-Agent/agent/pi_ext/vistr_video_tools.ts")).default(mock.api);
	const tools = {};
	for (const name of ["index_video", "read_video_sequence", "read_multiframe", "read_crop", "semantic_crop"]) {
		const t = mock.tools.get(name);
		assert.ok(t, `tool ${name} must be registered`);
		tools[name] = (params) => t.execute("call_" + name, params);
	}
	return { ...mock, stub, tools };
}

// ── index_video ──────────────────────────────────────────────────────
test("index_video: default 8-frame timeline, times within [0, dur-0.1]", async () => {
	const { tools, stub } = await makeTools({ caption: () => "t=0.00s: nothing\n" });
	assert.equal(process.env.VISTR_OBSERVER_API_KEY, undefined,
		"observer key must be removed before model-callable tools execute");
	const r = await tools.index_video({ path: testVideo() });
	const times = r.details.times;
	assert.equal(times.length, 8);
	assert.ok(times.every((t) => t >= 0 && t <= 1.9), `times out of range: ${times}`);
	assert.ok(times.every((t, i) => i === 0 || t > times[i - 1]), "times must be strictly ascending");
	assert.ok(textBlocks(r.content).includes("semantic timeline (8 sampled frames)"));
	assert.ok(textBlocks(r.content).includes("t=0.00s: nothing"));
	// caption call carries image_url blocks and max_tokens 1500
	// (thinking models need room for the forced <think> preamble + captions;
	// 1000 used to end inside the thinking block, returning content=null)
	const cap = stub.calls.find((c) => c.url.includes("/chat/completions"));
	assert.ok(cap, "caption VLM call must happen");
	assert.ok(cap.url.startsWith("http://observer.test/"));
	assert.equal(cap.headers.Authorization, "Bearer test-key");
	assert.equal(cap.headers["x-observer-test"], "configured");
	assert.equal(cap.body.max_tokens, 1500);
	assert.equal(cap.body.thinking, undefined,
		"non-DeepSeek observers must not receive DeepSeek-specific parameters");
	const contentArr = cap.body.messages[0].content;
	assert.ok(contentArr.some((b) => b.type === "image_url"), "caption call must embed frames");
});

test("index_video: num_frames clamped to [4, 12]", async () => {
	const { tools } = await makeTools({});
	assert.equal((await tools.index_video({ path: testVideo(), num_frames: 3 })).details.times.length, 4);
	assert.equal((await tools.index_video({ path: testVideo(), num_frames: 20 })).details.times.length, 12);
});

// ── read_video_sequence ──────────────────────────────────────────────
test("read_video_sequence: ordered frames across slice with labels", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_video_sequence({ path: testVideo(), start_s: 0.5, end_s: 1.5, num_frames: 4 });
	assert.equal(countImages(r.content), 4);
	const times = r.details.times;
	assert.deepEqual(times, [0.5, 0.8333333333333333, 1.1666666666666665, 1.5]);
	const txt = textBlocks(r.content);
	assert.ok(txt.includes("slice 0.50-1.50s"), txt);
	assert.ok(txt.includes("[frame 1/4 @ t=0.50s]"));
	assert.ok(txt.includes("[frame 4/4 @ t=1.50s]"));
});

test("read_video_sequence: num_frames clamped to [2, 8]", async () => {
	const { tools } = await makeTools({});
	assert.equal((await tools.read_video_sequence({ path: testVideo(), start_s: 0, end_s: 1, num_frames: 1 })).details.times.length, 2);
	assert.equal((await tools.read_video_sequence({ path: testVideo(), start_s: 0, end_s: 1, num_frames: 20 })).details.times.length, 8);
});

test("read_video_sequence: end_s clamped to dur-0.1", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_video_sequence({ path: testVideo(), start_s: 0, end_s: 99 });
	assert.equal(r.details.times.at(-1), 1.9);
});

test("read_video_sequence: reversed slice returns a friendly error", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_video_sequence({ path: testVideo(), start_s: 1.5, end_s: 0.5, num_frames: 4 });
	assert.equal(countImages(r.content), 0);
	assert.equal(r.details.times, undefined);
	assert.ok(textBlocks(r.content).includes("start_s must be less than or equal to end_s"));
});

// ── read_multiframe ──────────────────────────────────────────────────
test("read_multiframe: requested timestamps, out-of-range clamped", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_multiframe({ path: testVideo(), times_s: [0.1, 0.9, 5.0] });
	assert.deepEqual(r.details.times, [0.1, 0.9, 1.9]);
	assert.equal(countImages(r.content), 3);
	const txt = textBlocks(r.content);
	assert.ok(txt.includes("[frame 3/3 @ t=1.90s]"), txt);
});

test("read_multiframe: more than 8 timestamps truncated to 8", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_multiframe({ path: testVideo(), times_s: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9] });
	assert.equal(r.details.times.length, 8);
});

test("read_multiframe: empty timestamps returns a friendly error", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_multiframe({ path: testVideo(), times_s: [] });
	assert.equal(countImages(r.content), 0);
	assert.ok(textBlocks(r.content).includes("at least one finite timestamp"));
});

// ── read_crop ────────────────────────────────────────────────────────
test("read_crop: video + bbox -> pixel crop + details", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_crop({ path: testVideo(), time_s: 0.5, bbox: [200, 200, 600, 600] });
	assert.equal(countImages(r.content), 1);
	assert.deepEqual(r.details.pixels, [64, 48, 192, 144]); // /1000 * [320,240]
	assert.deepEqual(r.details.source, [320, 240]);
	assert.ok(textBlocks(r.content).includes("128×96px of 320×240"), textBlocks(r.content));
});

test("read_crop: details report the clamped frame timestamp", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_crop({ path: testVideo(), time_s: 99, bbox: [200, 200, 600, 600] });
	assert.equal(r.details.time_s, 1.9);
	assert.ok(textBlocks(r.content).includes("@ t=1.90s"));
});

test("read_crop: bbox out of [0,1000] is clamped", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_crop({ path: testVideo(), time_s: 0.5, bbox: [800, 0, 1200, 1000] });
	assert.deepEqual(r.details.pixels, [256, 0, 320, 240]);
});

test("read_crop: inverted bbox -> friendly error", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_crop({ path: testVideo(), time_s: 0.5, bbox: [600, 600, 200, 200] });
	assert.equal(countImages(r.content), 0);
	assert.ok(textBlocks(r.content).includes("too small after mapping"));
});

test("read_crop: tiny bbox -> friendly error", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_crop({ path: testVideo(), time_s: 0.5, bbox: [0, 0, 1, 1] });
	const txt = textBlocks(r.content);
	assert.ok(txt.includes("appears to use a 0-1 scale"), txt);
	assert.ok(txt.includes("0-1000"), txt);
});

test("read_crop: malformed bbox -> friendly error", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_crop({ path: testVideo(), time_s: 0.5, bbox: [100, 100, 500] });
	assert.equal(countImages(r.content), 0);
	assert.ok(textBlocks(r.content).includes("exactly four finite numbers"));
});

test("read_crop: video without time_s -> friendly error", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_crop({ path: testVideo(), bbox: [100, 100, 500, 500] });
	assert.ok(textBlocks(r.content).includes("provide time_s"));
});

test("read_crop: image path works without time_s", async () => {
	const { tools } = await makeTools({});
	const r = await tools.read_crop({ path: testImage(), bbox: [100, 100, 500, 500] });
	assert.equal(countImages(r.content), 1);
	assert.deepEqual(r.details.pixels, [32, 24, 160, 120]);
	assert.deepEqual(r.details.source, [320, 240]);
});

// ── semantic_crop ────────────────────────────────────────────────────
const SINGLE_CAND = {
	width: 320, height: 240,
	candidates: [{ id: 1, bbox: [100, 50, 200, 150], score: 0.9, phrase: "the ball" }],
	annotated_b64: "cmVjZWlwdA==",
};

const TWO_CAND = {
	width: 320, height: 240,
	candidates: [
		{ id: 1, bbox: [0, 0, 40, 40], score: 0.5, phrase: "a box" },
		{ id: 2, bbox: [100, 50, 200, 150], score: 0.4, phrase: "the ball" },
	],
	annotated_b64: "cmVjZWlwdA==",
};

test("semantic_crop: single candidate -> no selection subcall, receipt + crop", async () => {
	const { tools, stub } = await makeTools({ ground: () => SINGLE_CAND });
	const r = await tools.semantic_crop({ path: testImage(), target: "the ball" });
	assert.equal(countImages(r.content), 2); // receipt + crop
	assert.equal(r.details.selection_mode, "single");
	assert.equal(r.details.grounding_bbox.join(","), "100,50,200,150");
	assert.deepEqual(r.details.crop_bbox, [40, 0, 260, 220]); // S2.8 context ROI
	assert.equal(r.details.frame_size.join(","), "320,240");
	// no candidate-selection chat call
	assert.ok(!stub.calls.some((c) => c.url.includes("/chat/completions")),
		"single candidate must skip the VLM selection subcall");
});

test("semantic_crop: multiple candidates -> VLM selection subcall picks #2", async () => {
	let selectPrompt = null;
	const { tools, stub } = await makeTools({
		ground: () => TWO_CAND,
		select: (messages) => {
			selectPrompt = messages.flatMap((m) =>
				Array.isArray(m.content) ? m.content.filter((b) => b.type === "text").map((b) => b.text) : [])
				.join(" ");
			return "2";
		},
	});
	const r = await tools.semantic_crop({ path: testImage(), target: "the ball" });
	assert.equal(r.details.selection_mode, "vlm_select");
	assert.equal(r.details.grounding_bbox.join(","), "100,50,200,150");
	assert.ok(selectPrompt.includes("the ball"), `selection prompt should carry target: ${selectPrompt}`);
	assert.ok(selectPrompt.includes("1, 2"));
	const ground = stub.calls.find((c) => c.url.includes("/ground"));
	assert.equal(ground.body.topk, 6);
});

test("semantic_crop: no candidates -> friendly text, no crash", async () => {
	const { tools } = await makeTools({ ground: () => ({ width: 320, height: 240, candidates: [] }) });
	const r = await tools.semantic_crop({ path: testImage(), target: "ghost" });
	assert.equal(countImages(r.content), 0);
	assert.ok(textBlocks(r.content).includes("No region found"));
});

test("semantic_crop: video without time_s -> friendly error", async () => {
	const { tools } = await makeTools({ ground: () => SINGLE_CAND });
	const r = await tools.semantic_crop({ path: testVideo(), target: "the ball" });
	assert.equal(countImages(r.content), 0);
	assert.ok(textBlocks(r.content).includes("provide either time_s"));
});

test("semantic_crop: video + time_s works end-to-end", async () => {
	const { tools } = await makeTools({ ground: () => SINGLE_CAND });
	const r = await tools.semantic_crop({ path: testVideo(), target: "the ball", time_s: 1.0 });
	assert.equal(countImages(r.content), 2);
	assert.equal(r.details.time_s, 1.0);
	const txt = textBlocks(r.content);
	assert.ok(txt.includes("@ t=1.00s"));
});

test("semantic_crop: details report the clamped frame timestamp", async () => {
	const { tools } = await makeTools({ ground: () => SINGLE_CAND });
	const r = await tools.semantic_crop({ path: testVideo(), target: "the ball", time_s: 99 });
	assert.equal(r.details.time_s, 1.9);
	assert.ok(textBlocks(r.content).includes("@ t=1.90s"));
});

test("semantic_crop: VLM select replies garbage -> falls back to first candidate", async () => {
	const { tools } = await makeTools({ ground: () => TWO_CAND, select: () => "I don't know" });
	const r = await tools.semantic_crop({ path: testImage(), target: "the ball" });
	assert.equal(r.details.grounding_bbox.join(","), "0,0,40,40"); // falls back to id 1
});

// ── Thinking-model subcall replies (content null / reasoning present) ──
test("index_video: caption content+reasoning -> timeline from content, thinking in its own labeled block", async () => {
	const { tools } = await makeTools({
		caption: () => ({ content: "t=0.00s: nothing\n", reasoning: "let me examine the frames" }),
	});
	const r = await tools.index_video({ path: testVideo() });
	const txt = textBlocks(r.content);
	assert.ok(txt.includes("semantic timeline"), txt);
	assert.ok(txt.includes("t=0.00s: nothing"), txt);
	assert.ok(txt.includes("[caption subcall thinking]\nlet me examine the frames"), txt);
	// the reasoning must not leak into the timeline body itself
	const before = txt.split("[caption subcall thinking]")[0];
	assert.ok(!before.includes("let me examine"), "reasoning must stay in its labeled block");
});

test("index_video: caption content null (thinking-only reply) -> friendly error, no crash", async () => {
	const { tools } = await makeTools({
		caption: () => ({ content: null, reasoning: "thinking only, never committed an answer" }),
	});
	const r = await tools.index_video({ path: testVideo() });
	const txt = textBlocks(r.content);
	assert.equal(countImages(r.content), 0);
	assert.ok(txt.includes("no answer text"), txt);
	assert.ok(!txt.includes("Cannot read properties"), "must not surface the JS null-deref crash");
	assert.ok(txt.includes("[caption subcall thinking]\nthinking only"), txt);
	assert.equal(r.details.caption_ok, false);
});

test("semantic_crop: selection subcall gets enough tokens for a thinking model (>=128)", async () => {
	const { tools, stub } = await makeTools({ ground: () => TWO_CAND, select: () => "2" });
	await tools.semantic_crop({ path: testImage(), target: "the ball" });
	const sel = stub.calls.find((c) => c.url.includes("/chat/completions"));
	assert.ok(sel.body.max_tokens >= 128, `max_tokens=${sel.body.max_tokens} starves the thinking model`);
});

test("DeepSeek observer subcalls explicitly disable thinking", async () => {
	const { tools, stub } = await makeTools({
		caption: () => "t=0.00s: nothing\n",
		ground: () => TWO_CAND,
		select: () => "2",
	}, "https://api.deepseek.com");
	await tools.index_video({ path: testVideo() });
	await tools.semantic_crop({ path: testImage(), target: "the ball" });
	const calls = stub.calls.filter((c) => c.url.includes("/chat/completions"));
	assert.equal(calls.length, 2);
	for (const call of calls) {
		assert.deepEqual(call.body.thinking, { type: "disabled" });
	}
});

test("OpenRouter observer subcalls keep their existing request shape", async () => {
	const { tools, stub } = await makeTools({
		caption: () => "t=0.00s: nothing\n",
	}, "https://openrouter.ai/api/v1");
	await tools.index_video({ path: testVideo() });
	const call = stub.calls.find((c) => c.url.includes("/chat/completions"));
	assert.ok(call.url.startsWith("https://openrouter.ai/api/v1/"));
	assert.equal(call.body.thinking, undefined,
		"OpenRouter must not receive the DeepSeek-specific thinking field");
});

test("semantic_crop: selection content null (thinking-only reply) -> friendly error, no crash, no silent pick", async () => {
	const { tools } = await makeTools({
		ground: () => TWO_CAND,
		select: () => ({ content: null, reasoning: "deliberating but not committing" }),
	});
	const r = await tools.semantic_crop({ path: testImage(), target: "the ball" });
	const txt = textBlocks(r.content);
	assert.equal(countImages(r.content), 0, "no receipt/crop when selection failed");
	assert.ok(txt.includes("no answer text"), txt);
	assert.ok(!txt.includes("Cannot read properties"), "must not surface the JS null-deref crash");
	assert.ok(txt.includes("[selection subcall thinking]\ndeliberating"), txt);
	assert.equal(r.details.selection_mode, "vlm_select_failed");
});

test("semantic_crop: selection content+reasoning -> picks id from content, thinking labeled", async () => {
	const { tools } = await makeTools({
		ground: () => TWO_CAND,
		select: () => ({ content: "2", reasoning: "candidate 2 matches the ball" }),
	});
	const r = await tools.semantic_crop({ path: testImage(), target: "the ball" });
	assert.equal(r.details.grounding_bbox.join(","), "100,50,200,150"); // id 2
	assert.equal(r.details.selection_mode, "vlm_select");
	assert.ok(textBlocks(r.content).includes("[selection subcall thinking]\ncandidate 2 matches the ball"));
});

test("semantic_crop: select mentions several candidates -> last in-ids wins", async () => {
	const { tools } = await makeTools({ ground: () => TWO_CAND, select: () => "candidate 1 or 2" });
	const r = await tools.semantic_crop({ path: testImage(), target: "the ball" });
	assert.equal(r.details.grounding_bbox.join(","), "100,50,200,150"); // id 2 (last mentioned)
});

test("semantic_crop: select replies a number outside ids -> falls back to first candidate", async () => {
	const { tools } = await makeTools({ ground: () => TWO_CAND, select: () => "5" });
	const r = await tools.semantic_crop({ path: testImage(), target: "the ball" });
	assert.equal(r.details.grounding_bbox.join(","), "0,0,40,40"); // id 1
});
